//! Predefined recipe categories and tags — ported from `recipeDefaults.ts`.
//!
//! These are merged with any stored values in the **options** endpoint so the
//! selection dropdowns are always populated even on a fresh install.

pub const DEFAULT_CATEGORIES: &[&str] = &[
    // Meal type
    "Breakfast",
    "Brunch",
    "Lunch",
    "Dinner",
    "Snack",
    "Dessert",
    "Appetizer",
    "Side Dish",
    "Drink",
    // Dish style
    "Salad",
    "Soup",
    "Pasta",
    "Pizza",
    "Sandwich",
    "Bowl",
    "Stir-fry",
    "Baked",
    "Grilled",
    "Smoothie",
    // Cuisine
    "American",
    "Asian",
    "Belgian",
    "Chinese",
    "French",
    "Greek",
    "Indian",
    "Italian",
    "Japanese",
    "Korean",
    "Mexican",
    "Middle Eastern",
    "Mediterranean",
    "Spanish",
    "Thai",
    "Vietnamese",
    // Dutch
    "Ontbijt",
    "Diner",
    "Voorgerecht",
    "Bijgerecht",
    "Drank",
    "Salade",
    "Soep",
    "Roerbak",
    "Gebakken",
    "Gegrild",
    "Amerikaans",
    "Aziatisch",
    "Belgisch",
    "Chinees",
    "Frans",
    "Grieks",
    "Indiaas",
    "Italiaans",
    "Japans",
    "Koreaans",
    "Mexicaans",
    "Midden-Oosters",
    "Mediterraan",
    "Spaans",
    "Thais",
    "Vietnamees",
];

pub const DEFAULT_TAGS: &[&str] = &[
    // Dietary
    "Dairy-Free",
    "Gluten-Free",
    "Halal",
    "Keto",
    "Low-Calorie",
    "Low-Carb",
    "Low-Fat",
    "Paleo",
    "Plant-Based",
    "Vegan",
    "Vegetarian",
    "Whole30",
    // Effort & time
    "Easy",
    "Quick",
    "5 Ingredients",
    "One-Pot",
    "No-Cook",
    // Meal planning
    "Batch Cooking",
    "Budget-Friendly",
    "Freezer-Friendly",
    "Make-Ahead",
    "Meal Prep",
    // Occasion & audience
    "Comfort Food",
    "Date Night",
    "Kid-Friendly",
    "Party",
    // Flavour
    "High-Protein",
    "Healthy",
    "Light",
    "Spicy",
    "Sweet",
    "Hearty",
    // Dutch
    "Lactosevrij",
    "Glutenvrij",
    "Laagcalorisch",
    "Koolhydraatarm",
    "Laag in vet",
    "Plantaardig",
    "Veganistisch",
    "Vegetarisch",
    "Eenvoudig",
    "Snel",
    "5 ingrediënten",
    "Eén-pan",
    "Zonder koken",
    "Grote porties koken",
    "Budgetvriendelijk",
    "Diepvriesvriendelijk",
    "Voor te bereiden",
    "Maaltijdbereiding",
    "Troosteten",
    "Romantisch",
    "Kindvriendelijk",
    "Feest",
    "Rijk aan eiwit",
    "Gezond",
    "Licht",
    "Pittig",
    "Zoet",
    "Hartig",
];
