import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [],
  theme: {
    extend: {
      colors: {
        /** Culinary Atelier recipe/planner roles; RGB from CSS vars in `app/assets/css/tailwind.css`. */
        atelier: {
          canvas: 'rgb(var(--atelier-canvas) / <alpha-value>)',
          parchment: 'rgb(var(--atelier-parchment) / <alpha-value>)',
          'cream-error': 'rgb(var(--atelier-cream-error) / <alpha-value>)',
          'cream-warning': 'rgb(var(--atelier-cream-warning) / <alpha-value>)',
          'mint-success': 'rgb(var(--atelier-mint-success) / <alpha-value>)',
          ink: 'rgb(var(--atelier-ink) / <alpha-value>)',
          heading: 'rgb(var(--atelier-heading) / <alpha-value>)',
          muted: 'rgb(var(--atelier-muted) / <alpha-value>)',
          'field-label': 'rgb(var(--atelier-field-label) / <alpha-value>)',
          subtle: 'rgb(var(--atelier-subtle) / <alpha-value>)',
          chip: 'rgb(var(--atelier-chip) / <alpha-value>)',
          'chip-hover': 'rgb(var(--atelier-chip-hover) / <alpha-value>)',
          'image-well': 'rgb(var(--atelier-image-well) / <alpha-value>)',
          destructive: 'rgb(var(--atelier-destructive) / <alpha-value>)',
          'destructive-soft': 'rgb(var(--atelier-destructive-soft) / <alpha-value>)',
          'warm-accent': 'rgb(var(--atelier-warm-accent) / <alpha-value>)',
          'inverse-surface': 'rgb(var(--atelier-inverse-surface) / <alpha-value>)',
          'inverse-on-muted': 'rgb(var(--atelier-inverse-on-muted) / <alpha-value>)',
          'focus-ring': 'rgb(var(--atelier-focus-ring) / <alpha-value>)',
          cta: 'rgb(var(--atelier-cta) / <alpha-value>)',
          'cta-hover': 'rgb(var(--atelier-cta-hover) / <alpha-value>)',
          'cta-disabled': 'rgb(var(--atelier-cta-disabled) / <alpha-value>)',
          'primary-hover': 'rgb(var(--atelier-primary-hover) / <alpha-value>)',
          'primary-disabled': 'rgb(var(--atelier-primary-disabled) / <alpha-value>)',
          'error-foreground': 'rgb(var(--atelier-error-foreground) / <alpha-value>)',
          'warning-foreground': 'rgb(var(--atelier-warning-foreground) / <alpha-value>)',
          'success-foreground': 'rgb(var(--atelier-success-foreground) / <alpha-value>)',
          'neutral-action': 'rgb(var(--atelier-neutral-action) / <alpha-value>)',
          'icon-muted': 'rgb(var(--atelier-icon-muted) / <alpha-value>)',
          meta: 'rgb(var(--atelier-meta) / <alpha-value>)',
          description: 'rgb(var(--atelier-description) / <alpha-value>)',
          'entry-hover': 'rgb(var(--atelier-entry-hover) / <alpha-value>)',
          skeleton: 'rgb(var(--atelier-skeleton) / <alpha-value>)',
        },
        'inverse-primary': '#95d4b3',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#95d4b3',
        'on-tertiary-fixed-variant': '#4c4733',
        'secondary-fixed-dim': '#ffb783',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#301400',
        'outline-variant': '#bfc9c1',
        'secondary': '#944a00',
        'primary-container': '#2d6a4f',
        'on-tertiary-fixed': '#1f1c0b',
        'tertiary-fixed-dim': '#cec6ad',
        'primary': '#0f5238',
        'on-primary-fixed-variant': '#0e5138',
        'tertiary-container': '#655f4a',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e4e2e2',
        'on-background': '#1b1c1c',
        'surface-variant': '#e4e2e2',
        'tertiary-fixed': '#ebe2c8',
        'on-primary-fixed': '#002114',
        'on-tertiary-container': '#e2d9bf',
        'on-surface-variant': '#404943',
        'outline': '#707973',
        'on-secondary-fixed-variant': '#713700',
        'surface-container-high': '#eae8e7',
        'surface': '#fbf9f8',
        'inverse-on-surface': '#f2f0f0',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container': '#efeded',
        'on-surface': '#1b1c1c',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#663100',
        'surface-dim': '#dbd9d9',
        'background': '#fbf9f8',
        'secondary-container': '#fc8f34',
        'surface-container-low': '#f5f3f3',
        'primary-fixed': '#b1f0ce',
        'surface-bright': '#fbf9f8',
        'surface-tint': '#2c694e',
        'secondary-fixed': '#ffdcc5',
        'inverse-surface': '#303030',
        'on-primary-container': '#a8e7c5',
        'tertiary': '#4c4734',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      /** 44px at 16px root; see `MIN_TOUCH_TARGET_CSS_PX` in `app/constants/touchErgonomics.ts`. */
      minHeight: {
        touch: '2.75rem',
      },
      minWidth: {
        touch: '2.75rem',
      },
    },
  },
} satisfies Partial<Config>
